### ISSUE TITLE
fails on navigating to localhost:8080/otherwiki

### ISSUE THREAD

**Issue by sb3rg** [OokTech/TW5-MultiUser#15] opened 2018-03-21 17:54 UTC
Here is the error message:
`$:/core/modules/commands/wsserver.js:592
                $tw.loadPlugins(wikiInfo.plugins,$tw.config.pluginsPath,$tw.config.pluginsEnvVar);
                                         ^
TypeError: Cannot read property 'plugins' of null
    at Object.handler ($:/core/modules/commands/wsserver.js:592:42)
    at SimpleServer.requestHandler ($:/core/modules/commands/wsserver.js:321:15)
    at Server.emit (events.js:127:13)
    at parserOnIncoming (_http_server.js:642:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)`

Here are the Node Settings I am using:

{
"heartbeat": {
"interval":  "1000"  
} , 
"scripts": {
**"NewWiki":  "node ./tiddlywiki.js #wikiName --init #editionName"**  
} , 
"wikis": {
**"otherwiki":  "~/TiddlyWiki5/Wikis/SomeName"**  
} , 
"ws-server": {
"autoIncrementPort":  ""  , 
"host":  "0.0.0.0"  , 
"password":  ""  , 
"pathprefix":  ""  , 
"port":  "8080"  , 
"renderType":  "text/plain"  , 
"rootTiddler":  "$:/core/save/all"  , 
"serveType":  "text/html"  , 
"username":  ""  
  }  
}

My new _MultiUserWiki_ folder location is _~/TiddlyWiki5/Wikis/SomeName_

**Comment by inmysocks** [comment] 2018-03-22 10:09
Have you checked to make sure that there is actually a non-empty tiddlywiki.info file in the wiki folder? The error is from me not having a check to make sure that the there is a valid tiddlywiki.info file and you are seeing it because tiddlywiki can't find a working tiddlywiki.info file in the folder.

**Comment by sb3rg** [comment] 2018-03-22 18:29
Yes, I looked at the _~/TiddlyWiki5/Wikis/SomeName_ folder and i found the following files:
`example-start-script.sh  settings  tiddlers  tiddlywiki.info`
do I need to modify the tiddlywiki.info file in someway?

**Comment by sb3rg** [comment] 2018-03-22 18:31
This is what my tiddlywiki.info file looks like.  Does it need to have relative file paths, maybe?
{
    "description": "This is the demo edition for the MultiUser plugin created b$
    "plugins": [
        "OokTech/MultiUser"
    ],
    "themes": [
        "tiddlywiki/vanilla",
        "tiddlywiki/snowwhite",
        "OokTech/Mobile"
    ],
    "build": {
        "index": [
            "--rendertiddler",
            "$:/core/save/all",
            "index.html",
            "text/plain"
        ]
    }
}

**Comment by inmysocks** [comment] 2018-03-23 12:00
From what you have said here nothing looks wrong. But you don't need to use the multiuser edition for the other wikis, the plugin is included automatically by the server so you can make and edit normal (non-multiuser) wikis easily and then use them normally elsewhere.

And new updates to how the plugin works mean that this probably is probably irrelevant because it now uses another method to make other wikis that should prevent most places where errors can creep in. So try the newest version and if that works we will close this issue.

**Closed** 2018-03-26 22:28 UTC

**Comment by inmysocks** [comment] 2018-03-26 22:34
From your previous comment it sounds like you may not have updated to the new version, also if this is a new issue than yous should create a new issue for it.

Editing multiple wikis works on all the tests I have done so I am not sure what the issue is for you.

**Comment by sb3rg** [comment] 2018-03-26 22:53
Ah!  Yea... sorry, I'm not used to updating so often.  You are really on top of it!  Thank you for pointing that out.  Yes, it works now to create child wikis and even has a tab for adding wikis from node settings.  Awesome, dude!  Thank you, thank you, thank you.
